Repository SOPT-all/36-COLLABORATION-WEB-TEMU, pull requests merged in 2025-05, with the labels that each got.

#7 [deploy] 빌드 테스트중
  .github/workflows/ci-cd.yml
  index.html
Labels: 🔍CI/CD, 🌈 Deploy, 🐰희선

#12 [ci/cd] 빌드 자동화 테스트 (#6)
  .github/workflows/autoSync.yml
  .github/workflows/ci-cd.yml
Labels: 🔍CI/CD, 🐰희선

#2 [init/#1] pr 테스트
  index.html
Labels: 🎉Init, 🐰희선

#5 [init/#5] svg 세팅
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/svg/ic_arrow_down_gray.svg
  src/assets/svg/ic_arrow_down_gray_s.svg
  src/assets/svg/ic_arrow_down_white.svg
  src/assets/svg/ic_arrow_line_gray.svg
  src/assets/svg/ic_arrow_right_black.svg
  src/assets/svg/ic_arrow_right_gray.svg
  src/assets/svg/ic_arrow_right_green.svg
  src/assets/svg/ic_baby_black.svg
  src/assets/svg/ic_baby_white.svg
  src/assets/svg/ic_book_black.svg
  src/assets/svg/ic_book_white.svg
  src/assets/svg/ic_car_black.svg
  src/assets/svg/ic_car_white.svg
  src/assets/svg/ic_cart.svg
  src/assets/svg/ic_cart_black.svg
  src/assets/svg/ic_cart_gray7.svg
  src/assets/svg/ic_category.svg
  src/assets/svg/ic_check_green.svg
  src/assets/svg/ic_chevron_forward_black.svg
  src/assets/svg/ic_close.svg
  src/assets/svg/ic_digital_black.svg
  src/assets/svg/ic_digital_white.svg
  src/assets/svg/ic_flash_black.svg
  src/assets/svg/ic_flash_orange.svg
  src/assets/svg/ic_goods_black.svg
  src/assets/svg/ic_goods_white.svg
  src/assets/svg/ic_kitchen_black.svg
  src/assets/svg/ic_kitchen_white.svg
  src/assets/svg/ic_language.svg
  src/assets/svg/ic_necessity_black.svg
  src/assets/svg/ic_necessity_white.svg
  src/assets/svg/ic_page_left_gray.svg
  src/assets/svg/ic_page_right_gray.svg
  src/assets/svg/ic_plant_green.svg
  src/assets/svg/ic_recommend_black.svg
  src/assets/svg/ic_recommend_white.svg
  src/assets/svg/ic_return_green.svg
  src/assets/svg/ic_review_black.svg
  src/assets/svg/ic_review_filter.svg
  src/assets/svg/ic_review_white.svg
  src/assets/svg/ic_share.svg
  src/assets/svg/ic_shield_green.svg
  src/assets/svg/ic_sport_black.svg
  src/assets/svg/ic_sport_white.svg
  src/assets/svg/ic_star_2_sm.svg
  src/assets/svg/ic_star_3_sm.svg
  src/assets/svg/ic_star_4.svg
  src/assets/svg/ic_star_4_5.svg
  src/assets/svg/ic_star_4_5_sm.svg
  src/assets/svg/ic_star_4_sm.svg
  src/assets/svg/ic_star_5.svg
  src/assets/svg/ic_start_5_sm.svg
  src/assets/svg/ic_truck_green.svg
  src/assets/svg/ic_user.svg
  src/assets/svg/react.svg
  src/vite-env.d.ts
  vite.config.ts
Labels: 🎉Init, 🐶지우

#24 [init/#23] ESLint & Prettier 초기 세팅
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/setting.json
  eslint.config.js
  package.json
  pnpm-lock.yaml
Labels: 🎉Init, 🦊정훈

#28 [init/#27] style custom - theme 설정
  package.json
  pnpm-lock.yaml
  src/styles/theme.css.ts
  vite.config.ts
Labels: 🎉Init, 🐶지우

#20 [init/#3] path alias 설정
  package.json
  pnpm-lock.yaml
  src/App.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 🎉Init, 🐰희선

#21 [init/#22] 폴더 구조 세팅 & 라우팅 설정
  index.html
  package.json
  pnpm-lock.yaml
  src/App.css
  src/App.tsx
  src/api/.gitkeep
  src/assets/img/.gitkeep
  src/assets/svg/.gitkeep
  src/hooks/.gitkeep
  src/index.css
  src/main.tsx
  src/pages/.gitkeep
  src/router/Router.tsx
  src/shared/components/.gitkeep
  src/shared/constant/.gitkeep
  src/shared/hooks/.gitkeep
  src/shared/types/.gitkeep
  src/shared/utils/.gitkeep
  src/styles/.gitkeep
Labels: 🎉Init, 😽동희

#26 [init/#25] 글로벌 스타일 지정
  index.html
  package-lock.json
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/styles/reset.css.ts
  vite.config.ts
Labels: 🎉Init, 😽동희

#31 [init] 각 페이지 별 폴더 생성 및 라우터 처리
  src/pages/.gitkeep
  src/pages/home/Home.tsx
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productList/ProductList.tsx
  src/router/Router.tsx
  src/router/constant/routes.ts
Labels: ⭐Feature, 😽동희

#37 [init/#35] auto reviewer 설정 및 초기세팅 점검, svg 파일 index.ts 작성
  .github/CODEOWNERS
  .github/workflows/autoSync.yml
  .github/workflows/ci-cd.yml
  package.json
  src/App.tsx
  src/assets/svg/.gitkeep
  src/assets/svg/index.ts
  src/hooks/.gitkeep
  src/router/Router.tsx
  src/shared/styles/global.css.ts
  src/shared/styles/layers.css.ts
  src/shared/styles/reset.css.ts
  src/shared/styles/theme.css.ts
  src/styles/.gitkeep
  src/styles/global.css.ts
  src/styles/layers.css.ts
  src/vite-env.d.ts
  tsconfig.app.json
Labels: 🎉Init, 🐰희선

#44 [feat/#42] Text 공통 컴포넌트 구현
  package.json
  pnpm-lock.yaml
  src/shared/components/text/Text.css.ts
  src/shared/components/text/Text.tsx
Labels: ⭐Feat, 🐶지우

#38 [feat/#33] 버튼 공통 컴포넌트 구현
  src/assets/svg/ic_arrow_down_orange.svg
  src/assets/svg/index.ts
  src/shared/components/ProductActionButton/ProductActionButton.css.ts
  src/shared/components/ProductActionButton/ProductActionButton.tsx
Labels: ⭐Feat, 🦊정훈

#45 [feat/#43] Head 공통 컴포넌트 구현
  src/shared/components/head/Head.css.ts
  src/shared/components/head/Head.tsx
Labels: ⭐Feat, 🐶지우

#34 [feat/#32] card 공통 컴포넌트 생성
  src/assets/svg/ic_cart_black.svg
  src/assets/svg/ic_regular_customer.svg
  src/assets/svg/index.ts
  src/pages/home/Home.tsx
  src/shared/components/card/Card.css.ts
  src/shared/components/card/Card.tsx
Labels: ⭐Feat, 😽동희

#48 [refactor/#47] forwardRef 제거 및 ref prop 직접 전달 방식으로 변경
  src/shared/components/head/Head.tsx
Labels: 🪄Refactor, 🐶지우

#57 [feat/#56] 제품 상세보기 페이지 하단 nav버튼 구현
  src/pages/productDetail/components/detailTabs/DetailTabs.css.ts
  src/pages/productDetail/components/detailTabs/DetailTabs.tsx
  src/pages/productDetail/constant/TAB.ts
  src/shared/styles/theme.css.ts
Labels: ⭐Feat, 🐰희선

#60 [feat/#53] 제품 상세보기 페이지 하단 리뷰 테이블 구현
  src/assets/svg/ic_detail_review_graph.svg
  src/assets/svg/ic_star_1_5_sm.svg
  src/assets/svg/ic_star_1_sm.svg
  src/assets/svg/ic_star_2_5_sm.svg
  src/assets/svg/ic_star_3_5_sm.svg
  src/assets/svg/ic_star_5_sm.svg
  src/assets/svg/index.ts
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productDetail/productReviewSection/ProductReviewSection.css.ts
  src/pages/productDetail/productReviewSection/ProductReviewSection.tsx
  src/pages/productDetail/productReviewSection/components/nextPage/NextPage.css.ts
  src/pages/productDetail/productReviewSection/components/nextPage/NextPage.tsx
  src/pages/productDetail/productReviewSection/components/reviewFilterBar/ReviewFilterBar.css.ts
  src/pages/productDetail/productReviewSection/components/reviewFilterBar/ReviewFilterBar.tsx
  src/pages/productDetail/productReviewSection/components/reviewList/ReviewList.css.ts
  src/pages/productDetail/productReviewSection/components/reviewList/ReviewList.tsx
  src/pages/productDetail/productReviewSection/components/reviewListItem/ReviewListItem.css.ts
  src/pages/productDetail/productReviewSection/components/reviewListItem/ReviewListItem.tsx
  src/pages/productDetail/productReviewSection/components/reviewPhoto/ReviewPhoto.css.ts
  src/pages/productDetail/productReviewSection/components/reviewPhoto/ReviewPhoto.tsx
  src/pages/productDetail/productReviewSection/components/reviewSummary/ReviewSummary.css.ts
  src/pages/productDetail/productReviewSection/components/reviewSummary/ReviewSummary.tsx
  src/pages/productDetail/productReviewSection/constants/SUMMARY_SECTION.ts
  src/pages/productDetail/productReviewSection/constants/reviewData.ts
  src/pages/productDetail/productReviewSection/types/index.ts
  src/pages/productDetail/productReviewSection/types/reviews.ts
  src/pages/productDetail/productReviewSection/utils/getSortedReviews.ts
  src/shared/components/star/StarRating.tsx
  src/shared/components/star/starIcons.ts
Labels: ⭐Feat, 🦊정훈

#59 [feat/#58] 제품 상세보기 페이지 하단 제품 정보 테이블 구현
  src/pages/productDetail/constant/TABLE.ts
  src/pages/productDetail/detailTable/DetailTable.css.ts
  src/pages/productDetail/detailTable/DetailTable.tsx
  src/pages/productDetail/types/table.ts
  src/shared/styles/theme.css.ts
Labels: ⭐Feat, 🐰희선

#62 [refactor/#46] header footer
  src/assets/svg/index.ts
  src/shared/components/footer/components/footerBottom/FooterBottom.css.ts
  src/shared/components/footer/components/footerBottom/FooterBottom.tsx
  src/shared/components/footer/components/footerTop/FooterTop.css.ts
  src/shared/components/footer/constants/FOOTER_SECTIONS.ts
  src/shared/components/header/Header.css.ts
Labels: 🪄Refactor, 🐰희선

#64 [init/#63] Tanstack Query, api 연결 세팅
  .gitignore
  package.json
  pnpm-lock.yaml
  public/vite.svg
  src/App.tsx
  src/api/.gitkeep
  src/api/api.ts
  src/api/instance.ts
  src/api/queries.ts
  src/constant/queryKey.ts
  src/constant/url.ts
  src/pages/productDetail/types/response.ts
  src/shared/constant/.gitkeep
  src/shared/types/.gitkeep
  src/shared/types/api.ts
Labels: 🎉Init, 🐰희선

#68 [feat/#67] card 공통 컴포넌트 수정
  src/assets/svg/ic_day.svg
  src/assets/svg/index.ts
  src/pages/productList/ProductList.tsx
  src/pages/productList/mockData.ts
  src/pages/productList/types/api.ts
  src/shared/components/card/Card.css.ts
  src/shared/components/card/Card.tsx
  src/shared/components/card/constant/productTag.tsx
Labels: ⭐Feat, 😽동희

#52 [feat/#50] ProductDetail 페이지 상단부 구현
  eslint.config.js
  src/assets/svg/ic_share_white.svg
  src/assets/svg/index.ts
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productDetail/productTopSection/ProductTopSection.css.ts
  src/pages/productDetail/productTopSection/ProductTopSection.tsx
  src/pages/productDetail/productTopSection/components/bestSeller/BestSeller.css.ts
  src/pages/productDetail/productTopSection/components/bestSeller/BestSeller.tsx
  src/pages/productDetail/productTopSection/components/productImageGallery/ProductImageGallery.css.ts
  src/pages/productDetail/productTopSection/components/productImageGallery/ProductImageGallery.tsx
  src/pages/productDetail/productTopSection/components/productPurchasePanel/ProductPurchasePanel.css.ts
  src/pages/productDetail/productTopSection/components/productPurchasePanel/ProductPurchasePanel.tsx
  src/pages/productDetail/productTopSection/components/recommendedProducts/RecommendProducts.css.ts
  src/pages/productDetail/productTopSection/components/recommendedProducts/RecommendProducts.tsx
  src/pages/productDetail/productTopSection/constants/PURCHASE_PANEL.ts
  src/pages/productDetail/productTopSection/constants/mockDetailData.ts
  src/pages/productDetail/productTopSection/constants/mockRecommendData.ts
  src/shared/types/productDetailResponseTypes.ts
Labels: ⭐Feat, 🦊정훈

#39 [feat/#36] home 페이지 컴포넌트 구현
  eslint.config.js
  public/img/banner_familymonth.png
  public/img/familyMonthTitle.png
  public/img/imgMainBanner.png
  src/assets/svg/ic_baby_black.svg
  src/assets/svg/ic_book_black.svg
  src/assets/svg/ic_car_black.svg
  src/assets/svg/ic_digital_black.svg
  src/assets/svg/ic_goods_black.svg
  src/assets/svg/ic_kitchen_black.svg
  src/assets/svg/ic_necessity_black.svg
  src/assets/svg/ic_recommend_black.svg
  src/assets/svg/ic_sport_black.svg
  src/assets/svg/index.ts
  src/pages/home/Home.css.ts
  src/pages/home/Home.tsx
  src/pages/home/components/Tag.css.ts
  src/pages/home/components/Tag.tsx
  src/pages/home/components/constant/categorys.tsx
  src/pages/home/components/constant/tags.tsx
  src/pages/home/hooks/useFilterCard.tsx
  src/pages/home/mockHomeData.ts
  src/pages/home/types/api.ts
  src/shared/components/card/Card.tsx
  src/shared/styles/theme.css.ts
Labels: ⭐Feat, 😽동희

#66 [feat/#65] 제품 상세보기 페이지 상단 제외 구현
  .env
  src/pages/productDetail/ProductDetail.css.ts
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productDetail/components/detailTable/DetailTable.css.ts
  src/pages/productDetail/components/detailTable/DetailTable.tsx
  src/pages/productDetail/components/detailTabs/DetailTabs.css.ts
  src/pages/productDetail/components/detailTabs/DetailTabs.tsx
  src/pages/productDetail/constant/mockProductReviewData.ts
  src/pages/productDetail/productTopSection/ProductTopSection.css.ts
  src/pages/productDetail/productTopSection/components/productImageGallery/ProductImageGallery.css.ts
  src/pages/productDetail/productTopSection/components/recommendedProducts/RecommendProducts.css.ts
  src/router/Layout.tsx
  src/shared/components/ProductActionButton/ProductActionButton.tsx
  src/shared/components/head/Head.css.ts
  src/shared/components/header/Header.css.ts
  src/shared/components/header/Header.tsx
  src/shared/components/headerMid/HeaderMid.css.ts
  src/shared/styles/global.css.ts
Labels: ⭐Feat, 🐰희선

#70 [feat/#69] 제품 검색 api 연결
  package-lock.json
  src/api/api.ts
  src/api/queries.ts
  src/pages/productList/ProductList.css.ts
  src/pages/productList/ProductList.tsx
  src/pages/productList/mockData.ts
  src/pages/productList/types/api.ts
  src/pages/productList/types/response.ts
  src/shared/components/header/Header.tsx
Labels: ⭐Feat, 🐶지우

#78 [deploy/#77] main synk
  index.html
Labels: 🌈 Deploy, 🐰희선

#82 [chore/#81] 검색 아이콘에 검색 기능 연결
  src/shared/components/header/Header.tsx
Labels: 👾Chore, 🐶지우

#84 [fix/#83] 카드 컴포넌트 수정
  src/shared/components/card/Card.css.ts
  src/shared/components/card/Card.tsx
  src/shared/components/card/constant/productTag.tsx
Labels: 🔧 Fix, 🐶지우

#80 [style/#79] 상품 디테일 리뷰 UI 수정
  src/pages/productDetail/ProductDetail.css.ts
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productDetail/productReviewSection/ProductReviewSection.css.ts
  src/pages/productDetail/productReviewSection/ProductReviewSection.tsx
  src/pages/productDetail/productReviewSection/components/reviewListItem/ReviewListItem.css.ts
  src/pages/productDetail/productReviewSection/components/reviewSummary/ReviewSummary.css.ts
  src/pages/productDetail/productTopSection/ProductTopSection.css.ts
  src/pages/productDetail/productTopSection/ProductTopSection.tsx
Labels: 🎨Style, 🦊정훈

#87 [fix/#86] home banner height css 삭제
  src/pages/home/Home.css.ts
Labels: 🔧 Fix, 😽동희

#72 [feat/#71] 리뷰 api 연결 및 필터링 기능 추가
  src/api/api.ts
  src/api/queries.ts
  src/assets/svg/ic_detail_review_graph.svg
  src/pages/productDetail/productReviewSection/ProductReviewSection.tsx
  src/pages/productDetail/productReviewSection/components/reviewFilterBar/ReviewFilterBar.tsx
  src/pages/productDetail/productReviewSection/components/reviewSummary/ReviewSummary.css.ts
  src/pages/productDetail/productReviewSection/components/reviewSummary/ReviewSummary.tsx
  src/pages/productDetail/productReviewSection/constants/reviewData.ts
  src/pages/productDetail/productReviewSection/types/index.ts
  src/pages/productDetail/productReviewSection/types/reviews.ts
  src/pages/productDetail/productTopSection/constants/REVIEW_FILTER.ts
Labels: ⭐Feat, 🦊정훈

#74 [feat/#73] 제품 상세 api 연결 및 구매 패널 수량 선택 구현
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productDetail/productTopSection/ProductTopSection.tsx
  src/pages/productDetail/productTopSection/components/productImageGallery/ProductImageGallery.css.ts
  src/pages/productDetail/productTopSection/components/productImageGallery/ProductImageGallery.tsx
  src/pages/productDetail/productTopSection/components/productPurchasePanel/ProductPurchasePanel.css.ts
  src/pages/productDetail/productTopSection/components/productPurchasePanel/ProductPurchasePanel.tsx
  src/pages/productDetail/productTopSection/constants/PURCHASE_PANEL.ts
  src/pages/productDetail/productTopSection/constants/mockDetailData.ts
Labels: ⭐Feat, 🦊정훈

#91 [feat/#75] products promition api
  src/api/api.ts
  src/api/queries.ts
  src/pages/home/Home.tsx
  src/pages/home/types/api.ts
  src/shared/components/card/Card.css.ts
Labels: ⭐Feat, 😽동희

#95 [feat/#94] card 클릭 시, 스크롤 올리고 페이지 이동
  src/shared/components/card/Card.tsx
Labels: ⭐Feat, 😽동희

#98 [feat/#97] productDetail 페이지 추천상품 api 연동
  src/pages/productDetail/productTopSection/components/recommendedProducts/RecommendProducts.tsx
  src/pages/productDetail/productTopSection/constants/mockRecommendData.ts
  src/pages/productList/ProductList.tsx
Labels: ⭐Feat, 🦊정훈

#104 [hotfix/#103] response 타입 수정
  src/App.tsx
  src/api/api.ts
  src/api/queries.ts
  src/pages/home/Home.tsx
  src/pages/home/hooks/useFilterCard.tsx
  src/pages/home/mockHomeData.ts
  src/pages/home/types/response.ts
  src/pages/productDetail/productTopSection/components/recommendedProducts/RecommendProducts.tsx
  src/pages/productList/ProductList.tsx
  src/pages/productList/types/response.ts
Labels: 🐶지우, ⚠️HOTFIX

#100 [refactor/#99] 헤더 스크롤 방식 intersect observer 변경 & 카테고리 바깥 영역 클릭 이벤트
  .env
  .gitignore
  eslint.config.js
  src/pages/productList/ProductList.tsx
  src/shared/components/header/Header.css.ts
  src/shared/components/header/Header.tsx
  src/shared/components/headerMid/HeaderMid.tsx
  src/shared/hooks/.gitkeep
  src/shared/hooks/useIntersect.ts
  src/shared/hooks/useOutSideClick.ts
Labels: 🪄Refactor, 🐰희선

#105 [feat/#96] 검색 페이지 ui 수정
  src/pages/productList/ProductList.css.ts
  src/pages/productList/ProductList.tsx
Labels: ⭐Feat, 🐶지우

#109 [fix/#106] 제품 변경시 썸네일 이미지 초기화
  src/pages/productDetail/productTopSection/components/productImageGallery/ProductImageGallery.tsx
Labels: 🔧 Fix, 🦊정훈

#108 [chore/#107] 검색 시 결과 페이지 최상단으로 스크롤 이동
  src/pages/home/Home.css.ts
  src/shared/components/card/Card.css.ts
  src/shared/components/header/Header.css.ts
  src/shared/components/header/Header.tsx
Labels: 👾Chore, 🐶지우

#111 [feat/#110] 로딩 스피너, 경로 예외, 검색결과 없음, 깜빡임 현상 수정
  package.json
  pnpm-lock.yaml
  src/api/queries.ts
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productList/ProductList.tsx
  src/router/Layout.tsx
  src/router/Router.tsx
  src/shared/components/Error/ErrorSearch.css.ts
  src/shared/components/Error/ErrorSearch.tsx
  src/shared/components/Loading/Loading.css.ts
  src/shared/components/Loading/Loading.tsx
  src/shared/components/NotFound/NotFound.css.ts
  src/shared/components/NotFound/NotFound.tsx
  src/shared/styles/global.css.ts
  src/shared/styles/theme.css.ts
Labels: ⭐Feat, 🐰희선

#119 [fix/#117] 리뷰 별점 드롭다운 수정 & 리뷰 제품 없을때 문구 변경
  src/pages/productDetail/productReviewSection/ProductReviewSection.tsx
  src/pages/productDetail/productReviewSection/components/reviewFilterBar/ReviewFilterBar.css.ts
  src/pages/productDetail/productReviewSection/components/reviewFilterBar/ReviewFilterBar.tsx
  src/pages/productList/ProductList.tsx
  src/shared/components/Error/ErrorSearch.tsx
Labels: 🔧 Fix, 🦊정훈

#120 [fix/#118] 배포 사이트 404 에러 수정 & 상세 수정사항들 반영
  index.html
  src/pages/home/Home.css.ts
  src/pages/home/Home.tsx
  src/pages/home/components/ProductCardListContent/ProductCardListContent.css.ts
  src/pages/home/components/ProductCardListContent/ProductCardListContent.tsx
  src/pages/home/components/Tag/Tag.css.ts
  src/pages/home/components/Tag/Tag.tsx
  src/pages/home/components/productCardListSection/ProductCardListSecton.tsx
  src/pages/home/components/promotionCardList/PromotionCardList.tsx
  src/pages/productDetail/ProductDetail.tsx
  src/pages/productDetail/productTopSection/components/productPurchasePanel/ProductPurchasePanel.css.ts
  src/router/Layout.tsx
  src/shared/components/card/Card.css.ts
  src/shared/components/card/Card.tsx
  src/shared/components/header/Header.css.ts
  src/shared/components/header/Header.tsx
  src/shared/components/headerMid/HeaderMid.css.ts
  src/shared/components/headerMid/HeaderMid.tsx
  src/shared/components/headerMid/components/categoryMenu/CategoryMenu.css.ts
  src/shared/styles/global.css.ts
  vercel.json
Labels: 🔧 Fix, 🐰희선
